# Generated by Django 5.1.4 on 2024-12-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Funcionarios',
        ),
    ]
