# Generated by Django 5.1.4 on 2024-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_profissao_funcionario_remuneracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
